### ISSUE TITLE
Shizuku problem: not working with latest version of blocker

### ISSUE THREAD

**Issue by Algarues** [lihenggui/blocker#46]
When I try to disable any component I get a long series of errors starting with:

java.lang.RuntimeException: Problem connect to shizuku server

However shizuku is activated by adb and running.

Blocker does not appear in the list of authorized apps in Shizuku settings

**Comment by Efreak** [comment]
Happening here too

**Comment by lihenggui** [comment]
Updated.

**Comment by dhdkrystal** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Efreak** [comment]
Can you tag a new release so fdroid will rebuild? Or maybe @proletariat101 can update his ci on gitlab? Some of us don't have working Android dev environments.

**Comment by lihenggui** [comment]
> Can you tag a new release so fdroid will rebuild? Or maybe @proletarius101 can update his ci on gitlab? Some of us don't have working Android dev environments.

Let me check it

**Comment by lihenggui** [comment]
> Can you tag a new release so fdroid will rebuild? Or maybe @proletarius101 can update his ci on gitlab? Some of us don't have working Android dev environments.

The latest version contains Crashlytics, can we publish it on the fdroid?

**Comment by proletarius101** [comment]
Please exclude it in a fdroid build variant, or we'll have to patch it manually

**Comment by lihenggui** [comment]
https://github.com/lihenggui/blocker/commit/de0e4213127945bb3ba6cb20fe459af25c2afdf4 @proletarius101 Could you please check if this commit is enough?

I added a build flavor called 'basic', it excludes the crashlytics library.

**Comment by lihenggui** [comment]
And I think we can move the discussion to #22 @proletarius101 @Efreak

**Comment by MNLierman** [comment]
I understand from the description that a package modification is needed to change an app to “Test Application,” but I'm wondering if there's any way for this app to complete this task for me? If not is there a companion app that can do this.? Otherwise I find this app to be a bit misleading in claiming it has Shizuku support – as it doesn't work with Shizuku – no disrespect intended either, just frustrated and would like to reclaim my privacy, block apps from Auto starting or running in the background, etc. @lihenggui
